# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '17.0'

target 'BingoLingo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BingoLingo
  pod 'NMapsMap'
end
